language: python

python:
  - "3.7"
  - "3.8"
  - "3.9"
  - "3.10"
  - "3.11"
  - "3.12"

env:
  - DATEUTIL_VERSION=2.7.5
  - DATEUTIL_VERSION=2.8.0
  - DATEUTIL_VERSION=2.8.2

install:
  - pip install python-dateutil==$DATEUTIL_VERSION
  - pip install -e .
  - pip install pytest

script:
  - pytest
